services:
  postgresql:
    image: postgres:12.15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dimo
      - POSTGRES_PASSWORD=dimo
      - POSTGRES_DB=identity_api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
