LOG_LEVEL: debug
DB:
  USER: dimo
  PASSWORD: dimo
  PORT: 5432
  HOST: localhost
  NAME: identity_api
  MAX_OPEN_CONNECTIONS: 5
  MAX_IDLE_CONNECTIONS: 5
PORT: 3000
CONTRACT_EVENT_TOPIC: topic.contract.event
KAFKA_BROKERS: localhost:9092
DIMO_REGISTRY_CHAIN_ID: 31337
DIMO_REGISTRY_ADDR: "0x5eAA326fB2fc97fAcCe6A79A304876daD0F2e96c"
DIMO_VEHICLE_NFT_ADDR: "0xc6e7DF5E7b4f2A278906862b61205850344D4e7d"
AFTERMARKET_DEVICE_CONTRACT_ADDRESS: "0xcf9af64522162da85164a714c23a7705e6e466b3"
SYNTHETIC_DEVICE_CONTRACT_ADDRESS: "0x85226A67FF1b3Ec6cb033162f7df5038a6C3bAB2"
REWARDS_CONTRACT_ADDRESS: "0x375885164266d48C48abbbb439Be98864Ae62bBE"
BASE_IMAGE_URL: "https://devices-api.dev.dimo.zone/v1/"
TABLELAND_API_GATEWAY: "https://testnets.tableland.network/"
ETHEREUM_RPC_URL: "http://127.0.0.1:8545"
ENTRYPOINT_ADDR: "0x8104e3Ad430EA6d354d013A6789fDFc71E671c43"
