DB:
  USER: dimo
  PASSWORD: dimo
  PORT: 5432
  HOST: localhost
  NAME: identity_api
  MAX_OPEN_CONNECTIONS: 5
  MAX_IDLE_CONNECTIONS: 5
PORT: 3000
CONTRACT_EVENT_TOPIC: topic.contract.event
KAFKA_BROKERS: localhost:9094
DIMO_REGISTRY_CHAIN_ID: 31337
DIMO_REGISTRY_ADDR: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
DIMO_VEHICLE_NFT_ADDR: "0xc6e7DF5E7b4f2A278906862b61205850344D4e7d"
