DB:
  USER: dimo
  PASSWORD: dimo
  PORT: 5432
  HOST: localhost
  NAME: identity_api
  MAX_OPEN_CONNECTIONS: 5
  MAX_IDLE_CONNECTIONS: 5
PORT: 3000
CONTRACT_EVENT_TOPIC: topic.contract.event
KAFKA_BROKERS: localhost:9094
DIMO_REGISTRY_CHAIN_ID: 31337
