package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/DIMO-Network/identity-api/graph/model"
)

// Account is the resolver for the Account field.
func (r *queryResolver) Account(ctx context.Context, by model.AccountBy) (*model.Account, error) {
	return r.account.GetAccount(ctx, by)
}

// Accounts is the resolver for the Accounts field.
func (r *queryResolver) Accounts(ctx context.Context, first *int, after *string, last *int, before *string, filterBy *model.AccountFilter) (*model.AccountConnection, error) {
	return r.account.GetAccounts(ctx, first, after, last, before, filterBy)
}
