package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"github.com/DIMO-Network/identity-api/graph/model"
)

// Connections is the resolver for the connections field.
func (r *queryResolver) Connections(ctx context.Context, first *int, after *string, last *int, before *string) (*model.ConnectionConnection, error) {
	panic(fmt.Errorf("not implemented: Connections - connections"))
}
