package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"

	"github.com/DIMO-Network/identity-api/graph/model"
)

// Devicedefinition is the resolver for the devicedefinition field.
func (r *queryResolver) Devicedefinition(ctx context.Context, by model.DevicedefinitionBy) (*model.DeviceDefinition, error) {
	return r.deviceDefinition.GetDeviceDefinition(ctx, by)
}

// Devicedefinitions is the resolver for the devicedefinitions field.
func (r *queryResolver) Devicedefinitions(ctx context.Context, first *int, after *string, last *int, before *string, filterBy *model.DevicedefinitionFilter) (*model.DeviceDefinitionConnection, error) {
	return r.deviceDefinition.GetDeviceDefinitions(ctx, first, after, last, before, filterBy)
}
