package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"github.com/DIMO-Network/identity-api/graph/model"
)

// FindVehicleByID is the resolver for the findVehicleByID field.
func (r *entityResolver) FindVehicleByID(ctx context.Context, id int) (*model.Vehicle, error) {
	v, err := r.Repo.GetVehicle(ctx, id)
	if err != nil {
		return nil, err
	}

	return v, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
