package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/DIMO-Network/identity-api/graph/model"
	"github.com/ethereum/go-ethereum/common"
)

// Epochs is the resolver for the epochs field.
func (r *merklePoolResolver) Epochs(ctx context.Context, obj *model.MerklePool, first *int, after *string, last *int, before *string) (*model.MerkleEpochConnection, error) {
	return r.merkle.GetPoolEpochs(ctx, obj, first, after, last, before)
}

// Pool is the resolver for the pool field.
func (r *merkleRewardResolver) Pool(ctx context.Context, obj *model.MerkleReward) (*model.MerklePool, error) {
	pool, err := r.merkle.GetMerklePool(ctx, obj.PoolID)
	if err != nil {
		return nil, err
	}
	if pool == nil {
		return nil, fmt.Errorf("no pool with id %d", obj.PoolID)
	}
	return pool, nil
}

// MerklePools is the resolver for the merklePools field.
func (r *queryResolver) MerklePools(ctx context.Context, first *int, after *string, last *int, before *string) (*model.MerklePoolConnection, error) {
	return r.merkle.GetMerklePools(ctx, first, after, last, before)
}

// MerklePool is the resolver for the merklePool field.
func (r *queryResolver) MerklePool(ctx context.Context, poolID int) (*model.MerklePool, error) {
	return r.merkle.GetMerklePool(ctx, poolID)
}

// MerkleRewards is the resolver for the merkleRewards field.
func (r *queryResolver) MerkleRewards(ctx context.Context, account common.Address, poolID *int, claimed *bool, first *int, after *string, last *int, before *string) (*model.MerkleRewardConnection, error) {
	return r.merkle.GetMerkleRewards(ctx, account, poolID, claimed, first, after, last, before)
}

// MerklePool returns MerklePoolResolver implementation.
func (r *Resolver) MerklePool() MerklePoolResolver { return &merklePoolResolver{r} }

// MerkleReward returns MerkleRewardResolver implementation.
func (r *Resolver) MerkleReward() MerkleRewardResolver { return &merkleRewardResolver{r} }

type merklePoolResolver struct{ *Resolver }
type merkleRewardResolver struct{ *Resolver }
