package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"github.com/DIMO-Network/identity-api/graph/model"
	"github.com/DIMO-Network/identity-api/internal/controllers"
	"github.com/ethereum/go-ethereum/common"
)

// OwnedVehicles is the resolver for the ownedVehicles field.
func (r *queryResolver) OwnedVehicles(ctx context.Context, address common.Address) ([]*model.Vehicle, error) {
	vr := controllers.NewVehiclesCtrl(ctx, r.Db)
	return vr.GetOwnedVehicles(address)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
