package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"

	"github.com/DIMO-Network/identity-api/graph/model"
)

// Stakes is the resolver for the stakes field.
func (r *queryResolver) Stakes(ctx context.Context, first *int, after *string, last *int, before *string) (*model.StakeConnection, error) {
	return r.stake.GetDeveloperStakes(ctx, first, after, last, before)
}
