package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"

	"github.com/DIMO-Network/identity-api/graph/model"
)

// SyntheticDevice is the resolver for the syntheticDevice field.
func (r *queryResolver) SyntheticDevice(ctx context.Context, by model.SyntheticDeviceBy) (*model.SyntheticDevice, error) {
	panic(fmt.Errorf("not implemented: SyntheticDevice - syntheticDevice"))
}

// SyntheticDevices is the resolver for the syntheticDevices field.
func (r *queryResolver) SyntheticDevices(ctx context.Context, first *int, last *int, after *string, before *string, filterBy *model.SyntheticDevicesFilter) (*model.SyntheticDeviceConnection, error) {
	panic(fmt.Errorf("not implemented: SyntheticDevices - syntheticDevices"))
}
