package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"errors"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/DIMO-Network/identity-api/graph/model"
	"github.com/DIMO-Network/identity-api/internal/loader"
	"github.com/DIMO-Network/identity-api/internal/repositories"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// SyntheticDevice is the resolver for the syntheticDevice field.
func (r *queryResolver) SyntheticDevice(ctx context.Context, by model.SyntheticDeviceBy) (*model.SyntheticDevice, error) {
	sd, err := r.synthetic.GetSyntheticDevice(ctx, by)
	if err != nil {
		if errors.Is(err, repositories.ErrNotFound) {
			var msg string
			if by.Address != nil {
				msg = fmt.Sprintf("No synthetic device with address %s.", *by.Address)
			} else if by.TokenID != nil {
				msg = fmt.Sprintf("No synthetic device with token id %d.", *by.TokenID)
			}
			return nil, graphql.ErrorOnPath(ctx, &gqlerror.Error{
				Message: msg,
				Extensions: map[string]interface{}{
					"code": "NOT_FOUND",
				},
			})
		}
		return nil, err
	}
	return sd, nil
}

// SyntheticDevices is the resolver for the syntheticDevices field.
func (r *queryResolver) SyntheticDevices(ctx context.Context, first *int, last *int, after *string, before *string, filterBy *model.SyntheticDevicesFilter) (*model.SyntheticDeviceConnection, error) {
	return r.synthetic.GetSyntheticDevices(ctx, first, last, after, before, filterBy)
}

// IntegrationID is the resolver for the integrationId field.
func (r *syntheticDeviceResolver) IntegrationID(ctx context.Context, obj *model.SyntheticDevice) (int, error) {
	if obj.IntegrationID != 0 {
		return obj.IntegrationID, nil
	}

	// This is slightly wasteful, retrieving and formatting all of these fields, but we get to reuse code.
	conn, err := loader.GetConnection(ctx, 0, obj.ConnectionID)
	if err != nil {
		return 0, err
	}

	if conn.IntegrationID != nil {
		return *conn.IntegrationID, nil
	}

	return 0, nil
}

// Vehicle is the resolver for the vehicle field.
func (r *syntheticDeviceResolver) Vehicle(ctx context.Context, obj *model.SyntheticDevice) (*model.Vehicle, error) {
	return loader.GetVehicleByID(ctx, obj.VehicleID)
}

// Connection is the resolver for the connection field.
func (r *syntheticDeviceResolver) Connection(ctx context.Context, obj *model.SyntheticDevice) (*model.Connection, error) {
	return loader.GetConnection(ctx, obj.IntegrationID, obj.ConnectionID)
}

// SyntheticDevice returns SyntheticDeviceResolver implementation.
func (r *Resolver) SyntheticDevice() SyntheticDeviceResolver { return &syntheticDeviceResolver{r} }

type syntheticDeviceResolver struct{ *Resolver }
