package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/DIMO-Network/identity-api/graph/model"
)

// Sacds is the resolver for the sacds field.
func (r *accountResolver) Sacds(ctx context.Context, obj *model.Account, first *int, after *string, last *int, before *string) (*model.SacdConnection, error) {
	return r.accountsacd.GetSacdsForAccount(ctx, obj.Address, first, after, last, before)
}

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context, by model.AccountBy) (*model.Account, error) {
	// Only one option right now.
	if by.Address == nil {
		return nil, fmt.Errorf("must provide an address")
	}
	return &model.Account{
		Address: *by.Address,
	}, nil
}

// Account returns AccountResolver implementation.
func (r *Resolver) Account() AccountResolver { return &accountResolver{r} }

type accountResolver struct{ *Resolver }
