// Code generated by gitub.com/DIMO-Network/eventgen. DO NOT EDIT.
package connection

import (
	"math/big"

	"github.com/ethereum/go-ethereum/common"
)

var (
	TransferEventID         = common.HexToHash("0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef")
	ConnectionMintedEventID = common.HexToHash("0x16e7256a94e935dc419efa2b47bdb62ec5023b40947b172169eeb37b9b132686")
)

type Transfer struct {
	From    common.Address `json:"from"`
	To      common.Address `json:"to"`
	TokenId *big.Int       `json:"tokenId"`
}

type ConnectionMinted struct {
	Account              common.Address `json:"account"`
	ConnectionId         *big.Int       `json:"connectionId"`
	ConnectionAddr       common.Address `json:"connectionAddr"`
	ConnectionName       string         `json:"connectionName"`
	ConnectionType       [32]byte       `json:"connectionType"`
	ConnectionCostInDimo *big.Int       `json:"connectionCostInDimo"`
}
