apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "identity-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/trips/db/host
    secretKey: DB_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/trips/db/user
    secretKey: DB_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/trips/db/pass
    secretKey: DB_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/analytics/host
    secretKey: ELASTIC_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/analytics/username
    secretKey: ELASTIC_USERNAME
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/analytics/password
    secretKey: ELASTIC_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/trips/bundlr/private_key
    secretKey: BUNDLR_PRIVATE_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "identity-api.fullname" . }}-secret
    template:
      metadata: {}
