// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AccountSacd is an object representing the database table.
type AccountSacd struct {
	Account     []byte     `boil:"account" json:"account" toml:"account" yaml:"account"`
	Grantee     []byte     `boil:"grantee" json:"grantee" toml:"grantee" yaml:"grantee"`
	Permissions string     `boil:"permissions" json:"permissions" toml:"permissions" yaml:"permissions"`
	Source      string     `boil:"source" json:"source" toml:"source" yaml:"source"`
	TemplateID  null.Bytes `boil:"template_id" json:"template_id,omitempty" toml:"template_id" yaml:"template_id,omitempty"`
	CreatedAt   time.Time  `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	ExpiresAt   time.Time  `boil:"expires_at" json:"expires_at" toml:"expires_at" yaml:"expires_at"`

	R *accountSacdR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L accountSacdL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AccountSacdColumns = struct {
	Account     string
	Grantee     string
	Permissions string
	Source      string
	TemplateID  string
	CreatedAt   string
	ExpiresAt   string
}{
	Account:     "account",
	Grantee:     "grantee",
	Permissions: "permissions",
	Source:      "source",
	TemplateID:  "template_id",
	CreatedAt:   "created_at",
	ExpiresAt:   "expires_at",
}

var AccountSacdTableColumns = struct {
	Account     string
	Grantee     string
	Permissions string
	Source      string
	TemplateID  string
	CreatedAt   string
	ExpiresAt   string
}{
	Account:     "account_sacds.account",
	Grantee:     "account_sacds.grantee",
	Permissions: "account_sacds.permissions",
	Source:      "account_sacds.source",
	TemplateID:  "account_sacds.template_id",
	CreatedAt:   "account_sacds.created_at",
	ExpiresAt:   "account_sacds.expires_at",
}

// Generated where

type whereHelper__byte struct{ field string }

func (w whereHelper__byte) EQ(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelper__byte) NEQ(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelper__byte) LT(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelper__byte) LTE(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelper__byte) GT(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelper__byte) GTE(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_Bytes struct{ field string }

func (w whereHelpernull_Bytes) EQ(x null.Bytes) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Bytes) NEQ(x null.Bytes) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Bytes) LT(x null.Bytes) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Bytes) LTE(x null.Bytes) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Bytes) GT(x null.Bytes) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Bytes) GTE(x null.Bytes) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Bytes) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Bytes) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var AccountSacdWhere = struct {
	Account     whereHelper__byte
	Grantee     whereHelper__byte
	Permissions whereHelperstring
	Source      whereHelperstring
	TemplateID  whereHelpernull_Bytes
	CreatedAt   whereHelpertime_Time
	ExpiresAt   whereHelpertime_Time
}{
	Account:     whereHelper__byte{field: "\"identity_api\".\"account_sacds\".\"account\""},
	Grantee:     whereHelper__byte{field: "\"identity_api\".\"account_sacds\".\"grantee\""},
	Permissions: whereHelperstring{field: "\"identity_api\".\"account_sacds\".\"permissions\""},
	Source:      whereHelperstring{field: "\"identity_api\".\"account_sacds\".\"source\""},
	TemplateID:  whereHelpernull_Bytes{field: "\"identity_api\".\"account_sacds\".\"template_id\""},
	CreatedAt:   whereHelpertime_Time{field: "\"identity_api\".\"account_sacds\".\"created_at\""},
	ExpiresAt:   whereHelpertime_Time{field: "\"identity_api\".\"account_sacds\".\"expires_at\""},
}

// AccountSacdRels is where relationship names are stored.
var AccountSacdRels = struct {
}{}

// accountSacdR is where relationships are stored.
type accountSacdR struct {
}

// NewStruct creates a new relationship struct
func (*accountSacdR) NewStruct() *accountSacdR {
	return &accountSacdR{}
}

// accountSacdL is where Load methods for each relationship are stored.
type accountSacdL struct{}

var (
	accountSacdAllColumns            = []string{"account", "grantee", "permissions", "source", "template_id", "created_at", "expires_at"}
	accountSacdColumnsWithoutDefault = []string{"account", "grantee", "permissions", "source", "created_at", "expires_at"}
	accountSacdColumnsWithDefault    = []string{"template_id"}
	accountSacdPrimaryKeyColumns     = []string{"account", "grantee"}
	accountSacdGeneratedColumns      = []string{}
)

type (
	// AccountSacdSlice is an alias for a slice of pointers to AccountSacd.
	// This should almost always be used instead of []AccountSacd.
	AccountSacdSlice []*AccountSacd
	// AccountSacdHook is the signature for custom AccountSacd hook methods
	AccountSacdHook func(context.Context, boil.ContextExecutor, *AccountSacd) error

	accountSacdQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	accountSacdType                 = reflect.TypeOf(&AccountSacd{})
	accountSacdMapping              = queries.MakeStructMapping(accountSacdType)
	accountSacdPrimaryKeyMapping, _ = queries.BindMapping(accountSacdType, accountSacdMapping, accountSacdPrimaryKeyColumns)
	accountSacdInsertCacheMut       sync.RWMutex
	accountSacdInsertCache          = make(map[string]insertCache)
	accountSacdUpdateCacheMut       sync.RWMutex
	accountSacdUpdateCache          = make(map[string]updateCache)
	accountSacdUpsertCacheMut       sync.RWMutex
	accountSacdUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var accountSacdAfterSelectMu sync.Mutex
var accountSacdAfterSelectHooks []AccountSacdHook

var accountSacdBeforeInsertMu sync.Mutex
var accountSacdBeforeInsertHooks []AccountSacdHook
var accountSacdAfterInsertMu sync.Mutex
var accountSacdAfterInsertHooks []AccountSacdHook

var accountSacdBeforeUpdateMu sync.Mutex
var accountSacdBeforeUpdateHooks []AccountSacdHook
var accountSacdAfterUpdateMu sync.Mutex
var accountSacdAfterUpdateHooks []AccountSacdHook

var accountSacdBeforeDeleteMu sync.Mutex
var accountSacdBeforeDeleteHooks []AccountSacdHook
var accountSacdAfterDeleteMu sync.Mutex
var accountSacdAfterDeleteHooks []AccountSacdHook

var accountSacdBeforeUpsertMu sync.Mutex
var accountSacdBeforeUpsertHooks []AccountSacdHook
var accountSacdAfterUpsertMu sync.Mutex
var accountSacdAfterUpsertHooks []AccountSacdHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AccountSacd) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountSacdAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AccountSacd) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountSacdBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AccountSacd) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountSacdAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AccountSacd) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountSacdBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AccountSacd) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountSacdAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AccountSacd) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountSacdBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AccountSacd) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountSacdAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AccountSacd) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountSacdBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AccountSacd) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountSacdAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAccountSacdHook registers your hook function for all future operations.
func AddAccountSacdHook(hookPoint boil.HookPoint, accountSacdHook AccountSacdHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		accountSacdAfterSelectMu.Lock()
		accountSacdAfterSelectHooks = append(accountSacdAfterSelectHooks, accountSacdHook)
		accountSacdAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		accountSacdBeforeInsertMu.Lock()
		accountSacdBeforeInsertHooks = append(accountSacdBeforeInsertHooks, accountSacdHook)
		accountSacdBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		accountSacdAfterInsertMu.Lock()
		accountSacdAfterInsertHooks = append(accountSacdAfterInsertHooks, accountSacdHook)
		accountSacdAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		accountSacdBeforeUpdateMu.Lock()
		accountSacdBeforeUpdateHooks = append(accountSacdBeforeUpdateHooks, accountSacdHook)
		accountSacdBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		accountSacdAfterUpdateMu.Lock()
		accountSacdAfterUpdateHooks = append(accountSacdAfterUpdateHooks, accountSacdHook)
		accountSacdAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		accountSacdBeforeDeleteMu.Lock()
		accountSacdBeforeDeleteHooks = append(accountSacdBeforeDeleteHooks, accountSacdHook)
		accountSacdBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		accountSacdAfterDeleteMu.Lock()
		accountSacdAfterDeleteHooks = append(accountSacdAfterDeleteHooks, accountSacdHook)
		accountSacdAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		accountSacdBeforeUpsertMu.Lock()
		accountSacdBeforeUpsertHooks = append(accountSacdBeforeUpsertHooks, accountSacdHook)
		accountSacdBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		accountSacdAfterUpsertMu.Lock()
		accountSacdAfterUpsertHooks = append(accountSacdAfterUpsertHooks, accountSacdHook)
		accountSacdAfterUpsertMu.Unlock()
	}
}

// One returns a single accountSacd record from the query.
func (q accountSacdQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AccountSacd, error) {
	o := &AccountSacd{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for account_sacds")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AccountSacd records from the query.
func (q accountSacdQuery) All(ctx context.Context, exec boil.ContextExecutor) (AccountSacdSlice, error) {
	var o []*AccountSacd

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AccountSacd slice")
	}

	if len(accountSacdAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AccountSacd records in the query.
func (q accountSacdQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count account_sacds rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q accountSacdQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if account_sacds exists")
	}

	return count > 0, nil
}

// AccountSacds retrieves all the records using an executor.
func AccountSacds(mods ...qm.QueryMod) accountSacdQuery {
	mods = append(mods, qm.From("\"identity_api\".\"account_sacds\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"identity_api\".\"account_sacds\".*"})
	}

	return accountSacdQuery{q}
}

// FindAccountSacd retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAccountSacd(ctx context.Context, exec boil.ContextExecutor, account []byte, grantee []byte, selectCols ...string) (*AccountSacd, error) {
	accountSacdObj := &AccountSacd{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"identity_api\".\"account_sacds\" where \"account\"=$1 AND \"grantee\"=$2", sel,
	)

	q := queries.Raw(query, account, grantee)

	err := q.Bind(ctx, exec, accountSacdObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from account_sacds")
	}

	if err = accountSacdObj.doAfterSelectHooks(ctx, exec); err != nil {
		return accountSacdObj, err
	}

	return accountSacdObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AccountSacd) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no account_sacds provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accountSacdColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	accountSacdInsertCacheMut.RLock()
	cache, cached := accountSacdInsertCache[key]
	accountSacdInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			accountSacdAllColumns,
			accountSacdColumnsWithDefault,
			accountSacdColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(accountSacdType, accountSacdMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(accountSacdType, accountSacdMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"identity_api\".\"account_sacds\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"identity_api\".\"account_sacds\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into account_sacds")
	}

	if !cached {
		accountSacdInsertCacheMut.Lock()
		accountSacdInsertCache[key] = cache
		accountSacdInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AccountSacd.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AccountSacd) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	accountSacdUpdateCacheMut.RLock()
	cache, cached := accountSacdUpdateCache[key]
	accountSacdUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			accountSacdAllColumns,
			accountSacdPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update account_sacds, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"identity_api\".\"account_sacds\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, accountSacdPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(accountSacdType, accountSacdMapping, append(wl, accountSacdPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update account_sacds row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for account_sacds")
	}

	if !cached {
		accountSacdUpdateCacheMut.Lock()
		accountSacdUpdateCache[key] = cache
		accountSacdUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q accountSacdQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for account_sacds")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for account_sacds")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AccountSacdSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountSacdPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"identity_api\".\"account_sacds\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, accountSacdPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in accountSacd slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all accountSacd")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AccountSacd) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no account_sacds provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accountSacdColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	accountSacdUpsertCacheMut.RLock()
	cache, cached := accountSacdUpsertCache[key]
	accountSacdUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			accountSacdAllColumns,
			accountSacdColumnsWithDefault,
			accountSacdColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			accountSacdAllColumns,
			accountSacdPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert account_sacds, could not build update column list")
		}

		ret := strmangle.SetComplement(accountSacdAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(accountSacdPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert account_sacds, could not build conflict column list")
			}

			conflict = make([]string, len(accountSacdPrimaryKeyColumns))
			copy(conflict, accountSacdPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"identity_api\".\"account_sacds\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(accountSacdType, accountSacdMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(accountSacdType, accountSacdMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert account_sacds")
	}

	if !cached {
		accountSacdUpsertCacheMut.Lock()
		accountSacdUpsertCache[key] = cache
		accountSacdUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AccountSacd record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AccountSacd) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AccountSacd provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), accountSacdPrimaryKeyMapping)
	sql := "DELETE FROM \"identity_api\".\"account_sacds\" WHERE \"account\"=$1 AND \"grantee\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from account_sacds")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for account_sacds")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q accountSacdQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no accountSacdQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from account_sacds")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for account_sacds")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AccountSacdSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(accountSacdBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountSacdPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"identity_api\".\"account_sacds\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountSacdPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from accountSacd slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for account_sacds")
	}

	if len(accountSacdAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AccountSacd) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAccountSacd(ctx, exec, o.Account, o.Grantee)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccountSacdSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AccountSacdSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountSacdPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"identity_api\".\"account_sacds\".* FROM \"identity_api\".\"account_sacds\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountSacdPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AccountSacdSlice")
	}

	*o = slice

	return nil
}

// AccountSacdExists checks if the AccountSacd row exists.
func AccountSacdExists(ctx context.Context, exec boil.ContextExecutor, account []byte, grantee []byte) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"identity_api\".\"account_sacds\" where \"account\"=$1 AND \"grantee\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, account, grantee)
	}
	row := exec.QueryRowContext(ctx, sql, account, grantee)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if account_sacds exists")
	}

	return exists, nil
}

// Exists checks if the AccountSacd row exists.
func (o *AccountSacd) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AccountSacdExists(ctx, exec, o.Account, o.Grantee)
}
