// Code generated by SQLBoiler 4.17.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AftermarketDevices string
	DCNS               string
	DeveloperLicenses  string
	Manufacturers      string
	Privileges         string
	RedirectUris       string
	Rewards            string
	Signers            string
	SyntheticDevices   string
	VehicleSacds       string
	Vehicles           string
}{
	AftermarketDevices: "aftermarket_devices",
	DCNS:               "dcns",
	DeveloperLicenses:  "developer_licenses",
	Manufacturers:      "manufacturers",
	Privileges:         "privileges",
	RedirectUris:       "redirect_uris",
	Rewards:            "rewards",
	Signers:            "signers",
	SyntheticDevices:   "synthetic_devices",
	VehicleSacds:       "vehicle_sacds",
	Vehicles:           "vehicles",
}
