// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AftermarketDevices string
	DCNS               string
	Privileges         string
	SyntheticDevices   string
	Vehicles           string
}{
	AftermarketDevices: "aftermarket_devices",
	DCNS:               "dcns",
	Privileges:         "privileges",
	SyntheticDevices:   "synthetic_devices",
	Vehicles:           "vehicles",
}
